Added pid file handling Fixing stuck bug, proxy got stuck after some time

diff --git a/ssh_ssl_proxy/scripts/init.d/ssh_ssl_proxy b/ssh_ssl_proxy/scripts/init.d/ssh_ssl_proxy
--- a/ssh_ssl_proxy/scripts/init.d/ssh_ssl_proxy
+++ b/ssh_ssl_proxy/scripts/init.d/ssh_ssl_proxy
@@ -20,6 +20,8 @@ NAME=ssh_ssl_proxy
 DAEMON=/usr/sbin/$NAME
 DAEMON_ARGS="/etc/ssh_ssl_proxy.conf"
 SCRIPTNAME=/etc/init.d/$NAME
+VERBOSE="yes"
+PID_FILE="/var/run/ssh_ssl_proxy.pid"
 
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
@@ -44,7 +46,14 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --exec $DAEMON $DAEMON_ARGS || return 2
+	if [ ! -f "$PID_FILE" ]; then
+		touch "$PID_FILE"
+	fi
+	chown nobody:nogroup "$PID_FILE"
+	chmod u+r "$PID_FILE"
+	
+	start-stop-daemon --chuid nobody:nogroup --start --exec $DAEMON $DAEMON_ARGS
+	RETVAL="$?"
 }
 
 #
@@ -56,8 +65,8 @@ do_stop()
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --retry=TERM/30/KILL/5 --name $NAME
+	#   other if a failure occurred --retry=TERM/30/KILL/5
+	start-stop-daemon --stop --pidfile $PID_FILE
 	RETVAL="$?"
 	return "$RETVAL"
 }
